name: "Specific Tests"

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which specific test to run
        options:
          - issue_2
          - issue_3
        required: true
      additional_flags:
        type: string
        description: Additional pytest flags to pass
        default: ""
        required: false

jobs:
  test:
    name: "Test ${{ inputs.name }}"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Build library
        run: poetry build --format sdist
      - name: Install library
        run: python -m pip install dist/*.tar.gz
      - name: Install test requirements
        run: poetry install --only test --no-root --no-interaction
      - name: Run tests
        run: >-
          pytest -v -r a --import-mode=append 
          --cov=ultima --cov-report html:cov_html --cov-report term
          --specifically ${{ inputs.name }} ${{ inputs.additional_flags }}
